### ISSUE TITLE
MEG - Add support for using STI001-008 as stimulus triggers and STI009-016 as response channels

### ISSUE THREAD

**Issue by allermat** [MRC-CBU/BIDS_conversion#5]
As discussed with @olafhauk @RikHenson and @dcdace, when reading events from trigger channels: 
- convert STI001-STI008 to decimal and sum them up so we get stimulus trigger values up to 128
- separately handle STI009-STI016, convert them to decimal but don't sum them up. This way we get individual trigger values 256, 512 etc. for individual button presses

**Comment by allermat** [comment]
I thought I would do this in the config: 
event_channels can be a list of channels. In this case the behaviour is the same as now:
```python
event_channels = ['STI001', 'STI002', 'STI003', 'STI004', 'STI005', 'STI006', 'STI007', 'STI008']
```
or

```python
event_channels = ['STI101']
```
Alternatively event_channels can be a dictionary as follows: 
```python
event channels = dict(stim=['STI001', 'STI002', 'STI003', 'STI004', 'STI005', 'STI006', 'STI007', 'STI008'], \
                      resp=['STI009', 'STI010', 'STI011', 'STI012', 'STI013', 'STI014', 'STI015', 'STI016'])

```
This way the user can indicate which channels to use as stimulus and response channels. They would be handled (added up or not) as indicated in the initial comment. 

I will implement checks for the order of channels and if there are any missing ones particularly in the stimulus channels (e.g., if the user leaves out one from the middle of the list)

Any thoughts @RikHenson, @olafhauk, @dcdace?

**Comment by RikHenson** [comment]
I think either fine with me - whichever you think most elegant

**Comment by allermat** [comment]
OK, thanks. Just to clarify, I meant that both of these options will be still available, the user can choose depending on the level of control they want over the STI channel handling.

**Comment by allermat** [comment]
Hi @RikHenson, @dcdace, @olafhauk, 
This pull request should have solved this. Let me know if there's anything more needed regarding this issue.

**Comment by RikHenson** [comment]
Thanks Mate.

Your latest version runs ok for my subjects who have MRIs and had the correct STI0* stimulus and response channels saved in the FIF file.

However, there were a few subjects for whom there is no MRI – if the mri_* fields are set to “” (or null, or []?), can it just skip any attempt to convert?

Also, there were a few subjects for whom the RAs loaded the wrong project file during acquisition, so only the STI101 channel was saved (welcome to my world of large, multi-user projects where inevitable human error….!). In my version of your python script, it defaulted to STI101 if the channels in the config.py file did not exist – but I don’t think your code does this – could you add this default behaviour? (Note I don’t want to add STI101 to the config.py, because I think it would then use this for all subjects, which defeats purpose of being robust to overlapping triggers…)

Rik

PS Also, it might help the README to give an example event_info.json file with response codes, eg my one attached seems necessary if you want to allow for overlapping stimuli and responses, since your code requires a unique name for each possible unique trigger value.


---------------------------------------------------------------

Prof Richard Henson, MA, MSc, PhD, FBA
Professor of Cognitive Neuroscience, Department of Psychiatry, University of Cambridge
Director, Cambridge Centre for Ageing and Neuroscience (CamCAN)
President-Past, British Neuroscience Association
Fellow of the British Academy

MRC Cognition and Brain Sciences Unit
University of Cambridge
15 Chaucer Road
Cambridge, CB2 7EF
England
EMAIL:  ***@***.******@***.***>
URL:    http://www.mrc-cbu.cam.ac.uk/people/rik.henson/personal
DIRECT: +44 (0)1223 767 591
RECEPT: +44 (0)1223 355 294
MOBILE: +44 (0)794 1377 345

What is credible neuroscience?<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbnacredibility.org.uk%2F&data=05%7C01%7Caa2175%40universityofcambridgecloud.onmicrosoft.com%7Cf31fcc391c0841ef210808da7eb0ef59%7C49a50445bdfa4b79ade3547b4f3986e9%7C0%7C0%7C637961595642888764%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=38s8kijYwDNF2h4ZOSmyFpBI%2BC30eofD350Gg2J4AsE%3D&reserved=0>
---------------------------------------------------------------

**Comment by allermat** [comment]
Hi @RikHenson, 

Thanks for the feedback. 
> However, there were a few subjects for whom there is no MRI – if the mri_* fields are set to “” (or null, or []?), can it just skip any attempt to convert? 

This is in progress, see issue #10 
> Also, there were a few subjects for whom the RAs loaded the wrong project file during acquisition, so only the STI101 channel was saved (welcome to my world of large, multi-user projects where inevitable human error….!). In my version of your python script, it defaulted to STI101 if the channels in the config.py file did not exist – but I don’t think your code does this – could you add this default behaviour? (Note I don’t want to add STI101 to the config.py, because I think it would then use this for all subjects, which defeats purpose of being robust to overlapping triggers…) 

Sure, see issue #12 

> Also, it might help the README to give an example event_info.json file with response codes, eg my one attached seems necessary if you want to allow for overlapping stimuli and responses, since your code requires a unique name for each possible unique trigger value. 

Makes sense, see issue #13

**Comment by allermat** [comment]
With the above oustanding items assigned to their own issues, I'm closing this one.
